--- 
abstract: cursor class with built-in caching support
author: Matt S Trout <mst@shadowcat.co.uk> http://www.shadowcat.co.uk/
build_requires: 
  Cache::FileCache: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: DBIx-Class-Cursor-Cached
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0.08004
  Digest::SHA1: 0
  perl: 5.6.1
version: 1.000000
